name: Publish MapsIndoors Framework

on:
  push:
    tags:
      - '*'

jobs:
  release-mapsindoors-sdk:
    name: Make Github release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Create Github release
      uses: eloquent/github-release-action@v3
      with:
        assets: |
          - path: MapsIndoors*.xcframework.zip

  publish-mapsindoors-cocoapods:
    name: Publish Cocoapods
    needs: release-mapsindoors-sdk
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Cocoapods
      run: gem install cocoapods

    - name: Publish to Cocoapods
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      run: |
        pod trunk push MapsIndoors.podspec
        pod trunk push MapsIndoorsCore.podspec
        pod trunk push MapsIndoorsGoogleMaps.podspec
        pod trunk push MapsIndoorsMapbox.podspec

  post-to-slack:
    name: Slack Announcement
    needs: publish-mapsindoors-cocoapods
    runs-on: ubuntu-latest

    steps:
      - name: Announce New Version on Slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "text": "MapsIndoors ${{ github.ref }} for iOS is now available on https://cocoapods.org/pods/MapsIndoors"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
